import type { SourceLocation } from "./locations";
import type { BaseNode, Chunk, Identifier, Statement } from "./nodes";

type NodeArray = BaseNode[];
type OptionalNode = BaseNode | null;
type Range = [number, number];

interface FactoryModule {
  attachLoc<T extends BaseNode>(node: T, loc?: SourceLocation | null, range?: Range | null): T;
  makeChunk(body?: Statement[]): Chunk;
  makeBlock(body?: Statement[]): BaseNode;
  makeLocalStatement(variables: BaseNode[], init?: BaseNode[]): BaseNode;
  makeAssignmentStatement(variables: BaseNode[], init: BaseNode[]): BaseNode;
  makeCompoundAssignmentStatement(operator: string, variable: BaseNode, value: BaseNode): BaseNode;
  makeCallStatement(expression: BaseNode): BaseNode;
  makeFunctionDeclaration(options: Record<string, unknown>): BaseNode;
  makeFunctionExpression(options: Record<string, unknown>): BaseNode;
  makeIfStatement(clauses: BaseNode[], elseBody?: OptionalNode): BaseNode;
  makeIfExpression(clauses: BaseNode[], elseValue: BaseNode): BaseNode;
  makeWhileStatement(condition: BaseNode, body: BaseNode): BaseNode;
  makeRepeatStatement(condition: BaseNode, body: BaseNode): BaseNode;
  makeForNumericStatement(variable: BaseNode, start: BaseNode, end: BaseNode, step: OptionalNode, body: BaseNode): BaseNode;
  makeForGenericStatement(variables: BaseNode[], iterators: BaseNode[], body: BaseNode): BaseNode;
  makeDoStatement(body: BaseNode): BaseNode;
  makeReturnStatement(argumentsList?: BaseNode[]): BaseNode;
  makeBreakStatement(): BaseNode;
  makeContinueStatement(): BaseNode;
  makeLabelStatement(name: BaseNode): BaseNode;
  makeGotoStatement(name: BaseNode): BaseNode;
  makeTypeAliasStatement(name: BaseNode, typeParameters: BaseNode[], value: BaseNode): BaseNode;
  makeExportTypeStatement(name: BaseNode, typeParameters: BaseNode[], value: BaseNode): BaseNode;
  makeTypeFunctionStatement(options: Record<string, unknown>): BaseNode;
  makeExportTypeFunctionStatement(options: Record<string, unknown>): BaseNode;
  makeDeclareFunctionStatement(options: Record<string, unknown>): BaseNode;
  makeDeclareVariableStatement(name: BaseNode, annotation: BaseNode): BaseNode;
  makeFunctionName(base: Identifier, members?: Identifier[], method?: Identifier | null): BaseNode;
  makeAttribute(name: Identifier, args?: BaseNode[] | null, argumentStyle?: string | null): BaseNode;
  makeIdentifier(name: string): Identifier;
  makeNumericLiteral(value: number, raw?: string | null): BaseNode;
  makeStringLiteral(raw: string, value?: string): BaseNode;
  makeInterpolatedString(partsOrRaw: string | BaseNode[]): BaseNode;
  makeInterpolatedStringText(raw: string): BaseNode;
  makeBooleanLiteral(value: boolean): BaseNode;
  makeNilLiteral(): BaseNode;
  makeVarargLiteral(): BaseNode;
  makeUnaryExpression(operator: string, argument: BaseNode): BaseNode;
  makeBinaryExpression(operator: string, left: BaseNode, right: BaseNode): BaseNode;
  makeTypeAssertion(expression: BaseNode, annotation: BaseNode): BaseNode;
  makeGroupExpression(expression: BaseNode): BaseNode;
  makeMemberExpression(base: BaseNode, identifier: Identifier): BaseNode;
  makeIndexExpression(base: BaseNode, index: BaseNode): BaseNode;
  makeCallExpression(base: BaseNode, args?: BaseNode[]): BaseNode;
  makeMethodCallExpression(base: BaseNode, method: Identifier, args?: BaseNode[]): BaseNode;
  makeTableConstructor(fields?: BaseNode[]): BaseNode;
  makeTableField(kind: string, data: Record<string, unknown>): BaseNode;
  makeTableFieldIndex(key: BaseNode, value: BaseNode): BaseNode;
  makeTableFieldName(name: Identifier, value: BaseNode): BaseNode;
  makeTableFieldList(value: BaseNode): BaseNode;
  makeUnionType(types: NodeArray): BaseNode;
  makeIntersectionType(types: NodeArray): BaseNode;
  makeOptionalType(base: BaseNode): BaseNode;
  makeTypePack(value: BaseNode, postfix?: boolean): BaseNode;
  makeVariadicType(value: BaseNode): BaseNode;
  makeTypeLiteral(raw: string): BaseNode;
  makeTypeofType(expression: BaseNode): BaseNode;
  makeTypeReference(name: Identifier[], typeArguments?: BaseNode[]): BaseNode;
  makeTableType(fields?: BaseNode[]): BaseNode;
  makeTableTypeField(kind: string, data: Record<string, unknown>): BaseNode;
  makeTableTypeFieldIndex(key: BaseNode, value: BaseNode, access?: string | null): BaseNode;
  makeTableTypeFieldName(name: Identifier, value: BaseNode, access?: string | null): BaseNode;
  makeTableTypeFieldList(value: BaseNode): BaseNode;
  makeFunctionType(parameters: BaseNode[], returnTypes: BaseNode[], typeParameters?: BaseNode[]): BaseNode;
  makeParenthesizedType(value: BaseNode): BaseNode;
  makeTupleType(items: BaseNode[]): BaseNode;
  makeTypeParameter(name: Identifier | null, value: BaseNode): BaseNode;
}

const factory = require("./factory-impl") as FactoryModule;

export = factory;
